Update action.yml

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -18,6 +18,7 @@ jobs:
           run: |
             echo "REPO=$(jq -c -r '.repositories | map(.repo_name)' < ./repositories.json)" >> $GITHUB_OUTPUT 
             echo "$REPO"
+            
         - name: Set owner
           id: set-owner
           run: |
@@ -45,24 +46,32 @@ jobs:
           BBS_TOKEN: ${{ secrets.BBS_TOKEN }}
           OWNER: ${{ needs.Get-Repositories-to-Migrate.outputs.OWNER }}
           
+      - name: Check if repository exists
         run: |
-          ls
-          echo "${{ env.OWNER }}"
+          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GH_PAT }}" "https://api.github.com/repos/jgonzalez-clevermig-test/${{ matrix.repository }}")
 
+            # Verificar el código de respuesta
+            if [ "$response" -eq 200 ]; then
+              echo "El repositorio jgonzalez-clevermig-test/${{ matrix.repository }} existe."
+            else
+              echo "Error: El repositorio jgonzalez-clevermig-test/${{ matrix.repository }} no existe."
+              exit 1  # Salir con un código de error
+            fi
 
-      - name: Pull request
-        run: |
-          curl -X GET \
-          http://localhost:7990/rest/api/latest/projects/${{ env.OWNER }}/repos/repo-test/pull-requests \
-          -H 'Accept: application/json' \
-          -H 'Authorization: Bearer ${{ secrets.BBS_TOKEN }}' \
-          -o bbs_pullrequest.json
+      #- name: Pull request
+      #  run: |
+      #    curl -X GET \
+      #    http://localhost:7990/rest/api/latest/projects/${{ env.OWNER }}/repos/repo-test/pull-requests \
+      #    -H 'Accept: application/json' \
+      #    -H 'Authorization: Bearer ${{ secrets.BBS_TOKEN }}' \
+      #    -o bbs_pullrequest.json
           
       - name: Clone BitBucket Repository {{ item.bbs_repository_name }}
         run: |
           git clone http://${{ secrets.BBS_USERNAME }}:${{ secrets.BBS_PASSWORD }}@localhost:7990/scm/proj/${{ matrix.repository }}.git --mirror
-          cd ${{ matrix.repository }}.git
 
+      - name: Crate repository on Github
+        run: |
           curl -L \
             -X POST \
             -H "Accept: application/vnd.github+json" \
@@ -70,7 +79,10 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/orgs/jgonzalez-clevermig-test/repos \
             -d '{"name":"${{ matrix.repository }}","private":true}'
-          
+
+      - name: Push repository to Github
+        run: |
+          cd ${{ matrix.repository }}.git
           git remote add github "https://${{ secrets.GH_PAT }}@github.com/jgonzalez-clevermig-test/${{ matrix.repository }}.git"
           git push github --mirror
 
