Update action.yml

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -96,6 +96,13 @@ jobs:
           cd ${{ matrix.repository }}.git
           git remote add github "https://${{ secrets.GH_PAT }}@github.com/${{ env.ORGTARGET }}/${{ matrix.repository }}.git"
           git push github --mirror
+          if [ $? -eq 0 ]; then
+            echo "Push successful"
+            exit 0
+          else
+            echo "Push failed"
+            exit 1
+          fi
 
       - name: Set default branch
         run: |
@@ -104,14 +111,12 @@ jobs:
           
           # Realizar la solicitud GET con curl y almacenar la respuesta en una variable
           response=$(curl -s -H "Accept: application/json" -H "Authorization: Bearer ${{ secrets.BBS_TOKEN }}" "${url}")
-          
-          # Extraer el nombre del branch predeterminado usando jq y guardarlo en una variable
           default_branch=$(echo "${response}" | jq -r '.displayId')
           
-          # Imprimir el nombre del branch predeterminado
+          # Print default branch
           echo "Default Branch: ${default_branch}"
 
-          
+          # Set branch on Github Repository
           response=$(curl -s -X PATCH -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
           -d "{\"default_branch\": \"${default_branch}\"}" "https://api.github.com/repos/${{ env.ORGTARGET }}/${{ matrix.repository }}")
